name: html_to_pdf_example
description: Demonstrates how to use the html_to_pdf plugin.
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.0
  syncfusion_flutter_pdfviewer: ^24.1.46
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  html_to_pdf:
    path: ../


flutter:


  uses-material-design: true
  